# Generated by Django 2.2.7 on 2020-01-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict_app', '0003_auto_20200120_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
