# Generated by Django 2.2.7 on 2020-01-20 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ict_app', '0004_auto_20200120_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='posted_date',
        ),
    ]
