# Generated by Django 2.2.7 on 2020-01-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict_app', '0005_remove_blog_posted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='posted_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
