# Generated by Django 2.2.7 on 2020-01-20 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ict_app', '0006_blog_posted_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='posted_date',
        ),
    ]
