# Generated by Django 2.2.7 on 2020-01-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict_app', '0008_blog_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_pics'),
        ),
    ]
