# Generated by Django 2.2.7 on 2020-01-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict_app', '0012_blog_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('main_image', models.ImageField(upload_to='')),
                ('second_image', models.ImageField(upload_to='')),
                ('awards', models.PositiveSmallIntegerField()),
                ('articles', models.PositiveSmallIntegerField()),
                ('projects', models.PositiveSmallIntegerField()),
                ('card_title_1', models.CharField(max_length=250)),
                ('card_description_1', models.TextField()),
                ('card_title_2', models.CharField(max_length=250)),
                ('card_description_2', models.TextField()),
                ('card_title_3', models.CharField(max_length=250)),
                ('card_description_3', models.TextField()),
            ],
        ),
    ]
