# Generated by Django 2.2.7 on 2020-01-31 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict_app', '0013_about_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='approved_blog',
            field=models.BooleanField(default=False),
        ),
    ]
