# Generated by Django 2.2.7 on 2020-01-31 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ict_app', '0014_blog_approved_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved_comment',
        ),
    ]
