# Generated by Django 2.2.7 on 2020-01-31 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict_app', '0015_remove_comment_approved_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
