# Generated by Django 2.2.7 on 2020-01-31 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict_app', '0017_remove_blog_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=210)),
                ('image', models.ImageField(blank=True, null=True, upload_to='book_pics')),
                ('shared_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='books_file')),
            ],
        ),
        migrations.DeleteModel(
            name='Documents',
        ),
    ]
