# Generated by Django 2.2.7 on 2020-01-31 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict_app', '0019_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
