# Generated by Django 2.2.7 on 2020-01-31 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ict_app', '0020_course_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='content',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_link',
        ),
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
        migrations.RemoveField(
            model_name='course',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='course',
            name='title',
        ),
    ]
