# Generated by Django 2.2.7 on 2020-01-31 12:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ict_app', '0021_auto_20200131_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='content',
            field=models.TextField(default='Nothing'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_link',
            field=models.TextField(default='Nothing'),
        ),
        migrations.AddField(
            model_name='course',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course_images'),
        ),
        migrations.AddField(
            model_name='course',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.CharField(default='add', max_length=50),
        ),
    ]
